
import datetime

def logger(message, filename = ""):
    """Logs errors generated by the program if SAVE_LOGS flag is turned on
        Expected input:
        message: string or error
        optional filename: string
        Return: none
        Output: tab separated text file
    """
    #if used on multiple computers some synchronisation based on timezones would have to happen as well
    current_date = datetime.datetime.now().strftime("%Y-%m-%d")
    current_time = datetime.datetime.now().strftime("%H:%M:%S")
    message = str(message)
    if len(filename)==0:
        filename = message.split('"')[1]
    with open ("./logs/"+current_date+".txt", "a") as logfile:
        logfile.write(current_time+"\t"+filename+"\t"+message+"\n")


def log_reader():
    """Processes error logs"""
    #this would be a function to parse logs and find specific errors by file or date.
    pass